apiVersion: v1
kind: Service

metadata:
  name: bank-clusterip-service

spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: {{ .Values.app.bankService.port }}
  selector:
    service: bank
